#玩家加入服务器时发送Q群里面的话
Join:
  Message: "%Player%加入了服务器"
  sendQQ: true
#玩家退出服务器时发送Q群里面的话
Quit:
  Message: "%Player%退出了服务器"
  sendQQ: true
Minecraft:
  #发送群的服务器名字
  ServerName: "[MC服务器]"
  #触发文本
  Check: "群："
  #发送至QQ群的文本
  #变量：%Servername%服务器名字，%Player%玩家名字，%Message%玩家说的话
  Message: "%Servername%-%Player%:%Message%"
  #发送至玩家消息窗口的文本
  Say: "[%Servername%][群消息]%Message%"
  #机器人模式
  #0:不发送消息至QQ群，1:检测是否有触发文本，如果有就发送，2:无论玩家说什么，都发送到QQ群
  Mode: 1
  #是否开启在线人数显示
  SendMode: true
  #在线人数文本
  #变量：%Servername%服务器名字，%player_number%玩家数量，%player_list%所有玩家列表
  PlayerListMessage: "%Servername%当前在线人数：%player_number%，玩家列表：%player_list%"
  #服务器状态文本
  ServerOnlineMessage: "%Servername%服务器在线"
System:
  #机器人链接IP
  IP: "localhost"
  #机器人链接端口
  Port: 25555
  #是否启用自动重连
  AutoConnet: false
  #自动重连时间间隔
  AutoConnetTime: 10000
  #是否启用Debug模式
  Debug: false
  #数据包头
  Head: "[Head]"
  #数据包尾
  End: "[End]"
  #线程休眠，默认即可，如果你聊天的数量较多，请改小，单位毫秒
  Sleep: 50
User:
  #完成发送后是否提醒
  SendSucceed: true
  #完成发送后显示的文本
  SendSucceedMessage: "已发送消息至群内"
  #是否屏蔽玩家输入指令
  NotSendCommder: true
Logs:
  #是否记录群发来的消息
  Group: true
  #是否记录发送至群的消息
  Send: true
#配置文件版本号
Version: "2.2.4"
