name: Minecraft_QQ
main: Color_yr.Minecraft_QQ.Main.Bukkit
author: Color_yr
version: 2.1.3

commands:
  qq:
    description: Minecraft_QQ的主要指令
    permission: Minecraft_QQ.admin
    permission-message: 你没有这个权限
    usage: §4[Minecraft_QQ]§6/qq help来查看帮助
