name: Minecraft_QQ
main: Color_yr.Minecraft_QQ.Minecraft_QQBukkit
author: Color_yr
version: 2.7.0

loadbefore: [PlaceholderAPI]
softdepend: [PlaceholderAPI]

commands:
  qq:
    description: Minecraft_QQ的主要指令
    usage: §4[Minecraft_QQ]§6/qq help来查看帮助
